apiVersion: secretv2.rancher.jet.crossplane.io/v1alpha2
kind: Secret
metadata:
  name: crossplane-secret-v2
spec:
  forProvider:
    clusterId: local
    namespace: default
    dataSecretRef:
      foo:
        name: crossplane-test-secret
        namespace: crossplane-system
        key: name
  providerConfigRef:
    name: default

---

apiVersion: v1
kind: Secret
metadata:
  name: crossplane-test-secret
  namespace: crossplane-system
type: Opaque
stringData:
  name: crossplane
