apiVersion: rancher.jet.crossplane.io/v1alpha1
kind: CloudCredential
metadata:
  name: cc-aws
spec:
  forProvider:
    name: AWS Auth config by Crossplane
    amazonec2CredentialConfig:
      - accessKeySecretRef:
          name: cloud-credentials-secret
          namespace: crossplane-system
          key: accessKey
        secretKeySecretRef:
          name: cloud-credentials-secret
          namespace: crossplane-system
          key: secretKey
  providerConfigRef:
    name: default

---
    
apiVersion: rancher.jet.crossplane.io/v1alpha1
kind: CloudCredential
metadata:
  name: cc-google
spec:
  forProvider:
    name: Google Auth config by Crossplane
    googleCredentialConfig:
      - authEncodedJsonSecretRef:
          name: cloud-credentials-secret
          namespace: crossplane-system
          key: authEncodedJson
  providerConfigRef:
    name: default

---

apiVersion: v1
kind: Secret
metadata:
  name: cloud-credentials-secret
  namespace: crossplane-system
type: Opaque
stringData:
  accessKey: crossplane
  secretKey: t0ps3cr3t11
  authEncodedJson: '{ "token": "t0ps3cr3t11" }'
